### PR TITLE
escape field name on _$failedField

### LINKED ISSUE #1233: escaping invalid field names with a '$' breaks the generator on custom types
Our current problem:
We are building a builder that needs to generate custom Objects that can contain arbitrary field names and Types. We would like to escape invalid dart field names ba preceeding them with a `$`.
Like:
assert => $assert
class => $class
10 => $10

while this works when the field is one if Darts built in types this fails when we have custom types:
```dart
String get $assert;
int get $class;
DateTime get $10;
```
all work fine while:
```dart
CustomWhatever get $assert;
Custom get get $class;
Custom3 get $10;
```
all fail.

This can not be fixed by any suffix/prefix to the field name when being a number and only by a suffix on other reserved words:
```dart
CustomClass get johnDoeLoremIpsum$assert; //fails
CustomClass get johnDoe$10LoremIpsum // fails
CustomClass get $assertJohnDoe; // works
```
---

my guess is that the `$` isn't properly escaped somewhere (when creating the builder) thus it works for primitive dart types but doesn't for custom ones.

This means number fields without a letter are not possible :(

---

I've made a little POC for you to check out also appended below
https://github.com/Leptopoda/built_value_bug

```dart
abstract class BuggyClass implements Built<BuggyClass, BuggyClassBuilder> {
  const BuggyClass._();

  factory BuggyClass([
    void Function(BuggyClassBuilder)? b,
  ]) = _$BuggyClass;

  AnotherBuggyClass get $10;
}

abstract class AnotherBuggyClass
    implements Built<AnotherBuggyClass, AnotherBuggyClassBuilder> {
  const AnotherBuggyClass._();

  factory AnotherBuggyClass([
    void Function(AnotherBuggyClassBuilder)? b,
  ]) = _$AnotherBuggyClass;

  int get value1;
  int get value2;
}
```

fails generation with

```sh
➜  built_value_bug git:(main) ✗ dart pub run build_runner build
Deprecated. Use `dart run` instead.
[INFO] Generating build script completed, took 227ms
[INFO] Reading cached asset graph completed, took 37ms
[INFO] Checking for updates since last build completed, took 376ms
[SEVERE] built_value_generator:built_value on lib/built_value_bug.dart:
An error `FormatterException` occurred while formatting the generatesource for
  `package:built_value_bug/built_value_bug.dart`
which was output to
  `lib/built_value_bug.built_value.g.part`.
This may indicate an issue in the generator, the input source code, or in the
source formatter.
Could not format because the source could not be parsed:

line 90, column 19 of .: Expected an identifier.
   ╷
90 │ _$failedField = '$10'; $10.build();} catch (e) {
   │                   ^
   ╵
```

### PR DESCRIPTION
**Pull request by Leptopoda**
fixes #1233

Gonna sign the cla shortly.

### CODE REVIEW

**Comment by Leptopoda** [comment]
and signed :)

**Comment by davidmorgan** [comment]
Thanks! Could you please add to the examples under the `end_to_end_test` package so this is covered? That will also give coverage of any related issues.

I suggest adding field names with $ to `values_nnbd.dart`, and covering serialization by having the types declare a serializer and adding to `serializers_nnb.dart`.

You can run `tool/presubmit` to regenerate all the generated files and run tests.

Thanks :)

**Comment by Leptopoda** [comment]
done.
I thought it would fit nicely into `$ValueSpecial` and also added the serialization as requested.

File: end_to_end_test/lib/values_nnbd.dart [hunk 1]
```diff
@@ -7,6 +7,7 @@ import 'package:built_collection/built_collection.dart';
 import 'package:built_value/built_value.dart';
 import 'package:built_value/serializer.dart';
 import 'package:end_to_end_test/enums_nnbd.dart' as using_import_as;
+import 'package:end_to_end_test/values.dart';
```
Comment (davidmorgan) [inline end_to_end_test/lib/values_nnbd.dart:10]: It should work to remove this import, I think?

The presubmit is complaining because it's a "null safe" -> "legacy" import which isn't allowed.

Comment (Leptopoda) [reply end_to_end_test/lib/values_nnbd.dart]: Oh my IDE must have added this while I was poking around without noticing :sweat_smile:

And I was wondering why the tool gave me such a 'complex' exit code (at least it was green).
Sorry for not noticing :)

**Comment by davidmorgan** [comment]
Looks good now, thanks!

I'll aim to cut a release this week.
