### PR TITLE
Make generated deserialize method not throw cast_nullable_to_non_nullable lint warning

### LINKED ISSUE #1101: Generated code produces lint warning: cast_nullable_to_non_nullable
This is low priority, because I think most people exclude generated files from analysis. I wouldn't even see this if my exclude wasn't incorrectly setup just now.

The lint warning [is listed](https://dart-lang.github.io/linter/lints/cast_nullable_to_non_nullable.html) as experimental (as of December 16, 2021) but seems to be included by default in `package:lint`. It does seem like a good practice:

| Don't cast a nullable value to a non nullable type 

Screen Shot 2021-12-16 at 10 20 33

Right now, built_value generates deserialization code like this:

```dart
  @override
  Something deserialize(
      Serializers serializers, Iterable<Object?> serialized,
      {FullType specifiedType = FullType.unspecified}) {
    final result = new SomethingBuilder();

    final iterator = serialized.iterator;
    while (iterator.moveNext()) {
      final key = iterator.current as String;   // LINT HERE
      iterator.moveNext();
      final Object? value = iterator.current;
      switch (key) {
        case 'blah':
          result.blah = serializers.deserialize(value,
              specifiedType: const FullType(bool)) as bool;   // LINT HERE
          break;
      }
    }

    return result.build();
  }
```

The fix would be to add a null assert, for example:

```dart
final key = iterator.current! as String;
```

### PR DESCRIPTION
**Pull request by HelioStrike**
Fixes #1101.

The change adds a couple' null asserts to `deserialize` to prevent cast_nullable_to_non_nullable lint warning.

### CODE REVIEW

**Comment by HelioStrike** [comment]
Should I re-generate the generated files with the changed code?

File: built_value_generator/test/serializer_generator_test.dart [hunk 1]
```diff
@@ -226,6 +226,27 @@ abstract class _Value implements Built<_Value, _ValueBuilder> {
 }
 '''), contains(r'1. Cannot generate serializers for private class _Value'));
     });
+
+    test('deserialize is null safe', () async {
```
Comment (davidmorgan) [inline built_value_generator/test/serializer_generator_test.dart:230]: Thanks for the PR :)

Please add this as an end to end test rather than a unit test; the setup is that correct usage is tested as end to end tests, so we test the actual effect of the feature, and wrong usage is tested as unit tests, so we test the error output.

To add as an end to end test:

Run tool/use_local_deps so the end to end test uses the updated version of the generator. In the end_to_end_test folder you can now run the generation to iterate.

Add the lint to analysis_options.yaml for end_to_end_test. The lints are checked on presubmit, so this is now a test for the feature. Probably you don't need to add any new actual end to end cases to cover the feature.

Once it looks like it's working, try tool/presubmit. That regenerates everything, checks that it passes analysis (including lints), and runs all the tests. It's a bit slow though :)

Comment (HelioStrike) [reply built_value_generator/test/serializer_generator_test.dart:230]: I had to change a couple' small things and got the tool/presubmit to pass. That's a pretty neat test setup :)

Should I update the PR with newly generated code (after tool/presubmit) and the analysis_options change too, or just the little change I had to make to make tool/presubmit pass?

Comment (dave26199) [reply built_value_generator/test/serializer_generator_test.dart:230]: Please include everything in the pr :) thanks.

Comment (HelioStrike) [reply built_value_generator/test/serializer_generator_test.dart:230]: Updated the PR. Thanks!

Comment (HelioStrike) [reply built_value_generator/test/serializer_generator_test.dart:230]: Also, the presubmit tool seems to be using dartfmt, pub, and dartanalyzer which seem to be replaced with 'dart format', 'dart pub', and 'dart analyze' for the outside world. I think the recent push also contains these changes. Let me know if that's not ideal and I'll change the presuibmit tool script back.

Comment (davidmorgan) [reply built_value_generator/test/serializer_generator_test.dart:230]: Works for me, thanks :)

Change looks good, please also add to the changelog, something like:

# 8.2.0 (unreleased)

- Make generator output additional explicit null checks so the generated code complies with the `cast_nullable_to_non_nullable` lint.

Comment (HelioStrike) [reply built_value_generator/test/serializer_generator_test.dart:230]: Copy pasta and.... updated! Thanks! :)

Comment (davidmorgan) [reply built_value_generator/test/serializer_generator_test.dart:230]: Ah, sorry, one more, please remove the unit test :) ... the e2e test has this covered now, and unit tests on generated code are quite painful to maintain :) thanks!

Comment (HelioStrike) [reply built_value_generator/test/serializer_generator_test.dart]: Done, and no worries, thanks for being patient and pointing out all these little changes. :)

Comment (davidmorgan) [reply built_value_generator/test/serializer_generator_test.dart]: LG, thanks :)
