### PR TITLE
Make builder factory check `implName`-based

### LINKED ISSUE #835: Incorrect factory validation on _Builders
A custom builder `_Builder` will fail validation with `factory _Builder() = _$Builder`, asking instead for `_$_Builder`. However, it is the former that is generated.
```
Error in BuiltValueGenerator for

  abstract class _HomeSelectionSet with Home
    implements Built<_HomeSelectionSet, _HomeSelectionSetBuilder>.

Please make the following changes to use BuiltValue:
  1. Make builder class have exactly one factory:
    factory _HomeSelectionSetBuilder() = _$_HomeSelectionSetBuilder
```

(Not much of) a workaround is to use the `_$_Builder` statement for generation, then `s/_\$_/_$/g` in the source file, or simply don't use protected builders.

### PR DESCRIPTION
**Pull request by micimize**
closes #835 (I believe)

I just edited on github and haven't tested yet. Will test with a git dep shortly

### CODE REVIEW

**Comment by micimize** [comment]
tested and checks/generators are corrected

**Comment by micimize** [comment]
Just started implementing serialization and found what looks like a related issue there:
```
1. Declare _DimensionsSelectionSet.serializer as: static Serializer<_DimensionsSelectionSet> get serializer => _$_DimensionsSelectionSetSerializer; got static Serializer<_DimensionsSelectionSet> get serializer => _$dimensionsSelectionSetSerializer;
```

**Comment by micimize** [comment]
Ok, applied the same changes to serializers!

**Comment by micimize** [comment]
@davidmorgan anything else I need to do to move this forward?

**Comment by davidmorgan** [comment]
Sorry, I'm pretty snowed under at the moment.

I'll make sure this lands before the next `built_value` release--but, not sure right now when that will be!

Thanks for your patience :)

File: built_value_generator/lib/src/serializer_source_class.dart [hunk 1]
```diff
@@ -217,26 +217,45 @@ abstract class SerializerSourceClass
...
-          '_\$${camelCaseName}Serializer;';
+          'static Serializer<$name> get serializer => ${serializerInstanceName};';
       if (serializerDeclaration != expectedSerializerDeclaration &&
           serializerDeclaration != expectedSerializerDeclarationRaw) {
         result.add('Declare $name.serializer as: '
             '$expectedSerializerDeclaration got $serializerDeclaration');
       }
+      if (name.startsWith('_')) {
+        result.add('Cannot generate serializers for private class ${name}');
+      }
```
Comment (davidmorgan) [inline built_value_generator/lib/src/serializer_source_class.dart:258]: Looks like you can revert most of the changes to this class, since with this check generation for private classes is no longer needed?

File: built_value_generator/test/built_value_generator_test.dart [hunk 2]
```diff
@@ -745,6 +745,21 @@ abstract class Value implements Built<Value, ValueBuilder> {
         contains(
             '1. Set `nestedBuilders: false` in order to use `comparableBuilders: true`.'));
   });
+
+  test('Cleans generated class names for private classes', () async {
```
Comment (davidmorgan) [inline built_value_generator/test/built_value_generator_test.dart:749]: Please also add a private class to `end_to_end_test/lib/values.dart`.

File: built_value_generator/lib/src/serializer_source_class.dart (hunk 1 above)
Comment (micimize) [reply built_value_generator/lib/src/serializer_source_class.dart:258]: I could, but I don't really see the advantage – except maybe clarifying the doc comments. IMO leaving the `_` handling makes it more consistent with the rest of the code base, but with an explicit decision to disallow something, rather than a check to prevent something unimplemented.

We _can_ do this but we _aren't_ vs we _could_ do this but we _haven't_.
Matter of taste though – we can revert the changes if you prefer.

File: built_value_generator/test/built_value_generator_test.dart (hunk 2 above)
Comment (micimize) [reply built_value_generator/test/built_value_generator_test.dart:749]: Done!

File: built_value_generator/lib/src/serializer_source_class.dart (hunk 1 above)
Comment (davidmorgan) [reply built_value_generator/lib/src/serializer_source_class.dart:258]: I think somewhere in the middle is best :)

Extracting `serializerImplName` and `serializerInstanceName` is an improvement.

But, the `name.startsWith` check on line 256 guarantees that the corresponding checks in those two methods will always return false in any real situation, making that codepath unused and untested. Untested code is better removed if it can be :)

Thanks!

Comment (micimize) [reply built_value_generator/lib/src/serializer_source_class.dart:246]: @davidmorgan alright, cleaned up the dead code and rebased against master 👍

**Comment by davidmorgan** [comment]
Looks good, thanks! I'll add a CHANGELOG entry. Please let me know if you'd like an entry in AUTHORS, or just send a PR.
