### PR TITLE
Sound null serialization

### LINKED ISSUE #984: Deserializing with sound null safety is broken
Deserializing doesn't seem to work with sound null safety.
Here's a small example
```dart
import 'dart:convert';

import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';

part 'built_value_test.g.dart';

@SerializersFor([Login])
Serializers serializers = _$serializers;

void main(List<String> arguments) {
  var login = Login((b) => b
    ..username = 'johnsmith'
    ..password = '123456');
  print(json.encode(serializers.serialize(login)));
  serializers
      .deserialize(json.decode(json.encode(serializers.serialize(login))));
}

abstract class Login implements Built<Login, LoginBuilder> {
  String get username;
  String get password;
  Login._();
  factory Login([void Function(LoginBuilder)? updates]) = _$Login;
  static Serializer<Login> get serializer => _$loginSerializer;
}
```

Running the above example with sound null safety results in:
```
$ dart run
["Login","username","johnsmith","password","123456"]
Unhandled exception:
Deserializing '[Login, username, johnsmith, password, 123456]' to 'unspecified' failed due to: type 'List<dynamic>' is not a subtype of type 'List<Object>' in type cast
#0      BuiltJsonSerializers._deserialize (package:built_value/src/built_json_serializers.dart:143:11)
#1      BuiltJsonSerializers.deserialize (package:built_value/src/built_json_serializers.dart:121:18)
#2      main (file:///home/michael/devtestprojects/built_value_test/bin/built_value_test.dart:17:8)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

Running with `dart --no-sound-null-safety run` works fine.

### PR DESCRIPTION
**Pull request by davidmorgan**
Fix #984

### CODE REVIEW

**Review by iinozemtsev — APPROVED** [review]

File: built_value_generator/lib/src/serializer_source_class.dart [hunk 1]
```diff
@@ -304,25 +304,25 @@ abstract class SerializerSourceClass
...
   final Iterable<Type> types = const [$name, $implName];
   @override
   final String wireName = '${escapeString(wireName)}';
 
   @override
-  Iterable<Object> serialize(Serializers serializers, $genericName object,
+  Iterable<Object$orNull> serialize(Serializers serializers, $genericName object,
       {FullType specifiedType = FullType.unspecified}) {
-    ${fields.isEmpty ? 'return <Object>[];' : '''
+    ${fields.isEmpty ? 'return <Object$orNull>[];' : '''
```
Comment (gmlewis) [inline built_value_generator/lib/src/serializer_source_class.dart:316]: Pardon my intrusion, but I'm writing a Dart code parser, and came across this file in the Flutter distribution.

How is the Dart compiler supposed to decide whether the starting triple single quote (`'''`) on line 306 ends:
* here on line 316 or
* line 321 or
* below on line 328 or
* later on line 342 or
* what I think should be the correct answer, line 345 ?

Comment (davidmorgan) [reply built_value_generator/lib/src/serializer_source_class.dart:316]: The string interpolation expressions `${...}` completely hide any quotes inside them. Hopefully that's enough to get the right answer :)

Comment (miDeb) [reply built_value_generator/lib/src/serializer_source_class.dart:316]: Not sure how useful this is, but the formal grammar can be found here: https://dart.dev/guides/language/spec
